### ISSUE TITLE
Convert font icon to use SVGs

### ISSUE THREAD

**Issue by dcocchia** [instacart/Snacks#130]
Our `Icon` component currently relies on an icon font. This has many downsides for both end users of products and for developers implementing Snacks on their products. Our designers would like to use SVG icons for consistency, as well.

We'll maintain the same api for the `Icon` component as we do now with the exception of the `code` prop. The `code` prop will need to be removed, since SVGs do not use hexadecimal. That was never really a great idea in the first place, so best to kill it now before we do a more final release.

Should fix https://github.com/instacart/Snacks/issues/120
Will also fix the `String.fromCodePoint` issue from https://github.com/instacart/Snacks/issues/76

**Comment by dcocchia** [comment]
We'll also need to figure out exporting SVGs for use in other code bases. Not sure how tricky that will be 🤔

**Comment by spencerschack** [comment]
My thoughts were to use a loader that converted SVGs to react components.

**Comment by dcocchia** [comment]
That would solve a ton of issues, yeah. Maybe something like this lib https://github.com/smooth-code/svgr

**Comment by spencerschack** [comment]
Wow that is impressive

**Comment by dcocchia** [comment]
Fixed with https://github.com/instacart/Snacks/pull/155
