### ISSUE TITLE
Some Form components do not support theming

### ISSUE THREAD

**Issue by dcocchia** [instacart/Snacks#136]
It looks like a few of our Form components use hard coded colors, rather than using the `withTheme` HOC. Mostly it's just the outline color and icon color that would need updating. All are hard coded to `GREEN_500`

- [ ] Select
- [ ] FloatingLabel
- [ ] TextField

**Comment by nbwar** [comment]
https://github.com/instacart/Snacks/pull/137

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/Snacks/pull/137 Thanks @nbwar 👍
