### ISSUE TITLE
MenuItem onClick broken

### ISSUE THREAD

**Issue by timroesner** [instacart/Snacks#144]
I've tried both the latest release from master and the published version from npm and in both cases the onClick method of the MenuItem component is not called. 

I'm using this component in a DropdownMenu and the menu is successfully closed, but my own function is never called.

**Comment by dcocchia** [comment]
Can you post the code here for us to take a look at?

**Comment by dcocchia** [comment]
The `MenuItem` component does not have an `onClick` handler: https://instacart.github.io/Snacks/#menuitem

Instead, you'd define `onSelect` as a callback on the `DropDownMenu` component.

**Comment by dcocchia** [comment]
Yep, seeing the same issue. We'll take a look. For now, you can use the `onSelect` callback on the `DropdownMenu` component

**Comment by timroesner** [comment]
For `onSelect` is there a way to know which MenuItem has been selected?

**Comment by dcocchia** [comment]
Yep, `onSelect` is passed two arguments: the original click/keyup event and the option ie `onSelect(e, option)`

**Comment by nbwar** [comment]
@timroesner Why do you need an `onClick` event for each MenuItem rather than use the `onSelect` callback for  `DropDownMenu`?

**Comment by timroesner** [comment]
@nbwar Thank you, I wasn't aware that it was a design choice. Agreed onSelect is definitely the better way to handle selection
