### ISSUE TITLE
Borderless Buttons

### ISSUE THREAD

**Issue by spencerschack** [instacart/Snacks#145]
I need a button without a border.

Example:
<img width="336" alt="buttons" src="https://user-images.githubusercontent.com/1196158/38906486-d1a52828-426b-11e8-873e-8823ffff958c.png">

**Comment by spencerschack** [comment]
@dcocchia Is this worth adding or should I just pass in `style`?

**Comment by dcocchia** [comment]
This is the same as https://github.com/instacart/Snacks/issues/131 :)

**Comment by spencerschack** [comment]
I see
