### ISSUE TITLE
`supportsCSSGrid` fails on server rendering

### ISSUE THREAD

**Issue by tmarshall** [instacart/Snacks#150]
While building out a SSR setup I found that `Row` fails because of the `supportsCSSGrid` check on `navigator`.

We should update components to either:
- deal with situations where `navigator` or other global browser objects are not present
- move any of this logic to after a component is mounted (which will be on browser)

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/Snacks/pull/154
