### ISSUE TITLE
Greater than/less than breakpoints

### ISSUE THREAD

**Issue by spencerschack** [instacart/Snacks#151]
## What
Currently the media queries exported from `responsive` include only the single breakpoint section they are named after. I find it common to want a media query that represents "all viewport sizes greater than sm" etc.

## How
1. `xsSm`, `xsSmMd`, `xsSmMdLg`, `lgXl`, `mdLgXl`, `smMdLgXl` media queries.
2. `minSm`, `minMd`, `minLg`, `maxSm`, `maxMd`, `maxLg` media queries.
3. Helper `mediaQuery` that is used like `mediaQuery('sm, 'lg')` or `mediaQuery(null, 'md')`

## Thoughts
1 and 2 don't address media queries that are some grouping of breakpoint sections that are not boundless on one end. 3 is complicated. 1 is not really an option because of the `mdLg` breakpoint.

**Comment by dcocchia** [comment]
Yeah, totally need something like this. @wfro had some good thoughts on this, as well. I think he may have even started on something. If he doesn't comment here, can you sync with him and post what you come up with here?

**Comment by dcocchia** [comment]
Material has a really interesting way of doing this: https://material-ui-next.com/layout/css-in-js/

```js
style = {
  [theme.breakpoints.up('md')]: {
    backgroundColor: 'red',
  }
}
```

**Comment by spencerschack** [comment]
+1 for that approach

**Comment by wfro** [comment]
Yep, I really want these as well :) so I’ll try and wrap this up early next week. The bootstrap 4 responsive mixins api is good so I just copied that for the most part. there’s up/down/only and I think between? https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints

**Comment by spencerschack** [comment]
Awesome! Let me know if you want any help.

**Comment by scottjason** [comment]
nice 👍

**Comment by dcocchia** [comment]
Implemented in https://github.com/instacart/Snacks/pull/153

**Comment by spencerschack** [comment]
Thanks @wfro!!!
