### ISSUE TITLE
Radio buttons and RadioGroup don't work properly

### ISSUE THREAD

**Issue by nbwar** [instacart/Snacks#165]
### Radio
`Radio` doesn't work when using in separate project unless the sprite.svg file is in a public folder.
The Radio tries to fetch the styling from `localhost:3000/sprite.svg` see: `<use xlinkHref={`sprite.svg#${svgSprite.id}`} />` 

### RadioGroup
`RadioGroup` doesn't work as a controller component. The `selectedBtn` prop to make it work as a controlled component needs to be type `Radio` where it should be a string value.

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/Snacks/pull/173
Releasing with https://github.com/instacart/Snacks/pull/176
