### ISSUE TITLE
Remove underscore, use lodash instead or create our own utilities

### ISSUE THREAD

**Issue by dcocchia** [instacart/Snacks#178]
Underscore is a very large dependency that we're only using sparingly. The entire lib gets included, since it's not very tree-shakable. Let's either move to lodash or create our own set of utils.

**Comment by Brantron** [comment]
there are currently only 2-3 underscore functions being used. I think just replacing those functions would be the right call.

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/Snacks/pull/237
