### ISSUE TITLE
Update the spacing module to only use longhand values

### ISSUE THREAD

**Issue by mmarcuccio** [instacart/Snacks#246]
Using a mix of shorthand and longhand values creates warnings in Radium.  We should update spacing.* to only export longhand values.

Before:
```javascript
spacing.PADDING_SM  // => { padding: 16 }
```

After:
```javascript
spacing.PADDING_SM  // => { paddingTop: 16, paddingRight: 16, paddingBottom: 16, paddingLeft: 16 }
```

**Comment by Brantron** [comment]
I turned warnings off in dev because this is so severe. This would be awesome if someone wanted to take it on
