### ISSUE TITLE
Remove padding/margin shorthand css property usage from Snacks components

### ISSUE THREAD

**Issue by mmarcuccio** [instacart/Snacks#254]
Since we are refactoring the spacing module to address margin/padding, we should do the same for the styles applied to Snacks components.

Example of this issue: https://github.com/instacart/Snacks/blob/51312c3a9452bd50c682ce92c524b55cf10deb7a/src/components/Pill/Pill.js#L15

**Comment by dcocchia** [comment]
Fixed in https://github.com/instacart/Snacks/pull/252

**Comment by dcocchia** [comment]
Oops, never mind. Different issue - reopening
