### ISSUE TITLE
Inconsistent use of style vs styles prop

### ISSUE THREAD

**Issue by dcocchia** [instacart/Snacks#98]
Some components allow users to style using the `style` prop and others use `styles`. We should standardize this to `style`, to match the React API. 

Components using `styles` that need to be updated:
- ~~**Checkbox**: https://instacart.github.io/Snacks/#checkbox~~
- ~~**Radio**: https://instacart.github.io/Snacks/#radio~~
- ~~**RadioGroup**: https://instacart.github.io/Snacks/#radiogroup~~
- **CircleButton**: https://instacart.github.io/Snacks/#circlebutton
- **Grid**: https://instacart.github.io/Snacks/#grid
- **Row**: https://instacart.github.io/Snacks/#row

**Comment by dcocchia** [comment]
@julianhr will you take on the Radio, Checkbox and RadioGroup ones?

I'll take on the CircleButton, Grid, Row, and ScrollTrack.

**Comment by julianhr** [comment]
@dcocchia yes, I'll work on them.

**Comment by julianhr** [comment]
@dcocchia fix added via https://github.com/instacart/Snacks/pull/99

**Comment by dcocchia** [comment]
Circle button fix: https://github.com/instacart/Snacks/pull/101
Grid and Row fix: https://github.com/instacart/Snacks/pull/102

Will merge these in and create a new release, since this is our first real breaking change for the Instacart app.

**Comment by dcocchia** [comment]
Issues are all fixed as of v0.0.68
